{% set name = "kwidgetsaddons" %}
{% set version = "5.74.0" %}
{% set major_minor = ".".join(version.split(".")[:2]) %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://download.kde.org/stable/frameworks/{{ major_minor }}/kwidgetsaddons-{{ version }}.tar.xz
  sha256: 5b61c13a6ebb1e248fe38bd3912919f4bf6be93d74bb2f8b1d97caf6dd9a2342

build:
  number: 0
  skip: true  # [not linux]
  run_exports:
    - {{ pin_subpackage('kwidgetsaddons', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make
    - extra-cmake-modules >={{ version }}
    - {{ cdt('mesa-libgl-devel') }}  # [linux]
    - {{ cdt('mesa-dri-drivers') }}  # [linux]
    - {{ cdt('libselinux') }}  # [linux]
    - {{ cdt('libxdamage') }}  # [linux]
    - {{ cdt('libxxf86vm') }}  # [linux]
  host:
    - xorg-libxfixes  # [linux]
    - xorg-libxext
    - qt

test:
  commands:
    - test -f ${PREFIX}/lib/libKF5WidgetsAddons.so

about:
  home: https://api.kde.org/frameworks/kwidgetsaddons/html/index.html
  license: BSD-3-Clause AND GPL-2.0-or-later AND LGPL-2.0-only AND LGPL-2.0-or-later AND LGPL-2.1-only AND LGPL-2.1-or-later AND LGPL-3.0-only AND LGPL-3.0-or-later AND LicenseRef-KDE-Accepted-LGPL
  license_family: GPL
  license_file:
    - LICENSES/BSD-3-Clause.txt
    - LICENSES/GPL-2.0-or-later.txt
    - LICENSES/LGPL-2.0-only.txt
    - LICENSES/LGPL-2.0-or-later.txt
    - LICENSES/LGPL-2.1-only.txt
    - LICENSES/LGPL-2.1-or-later.txt
    - LICENSES/LGPL-3.0-only.txt
    - LICENSES/LGPL-3.0-or-later.txt
    - LICENSES/LicenseRef-KDE-Accepted-LGPL.txt
  summary: Large set of desktop widgets
  description: |
    This repository contains add-on widgets and classes for applications that
    use the Qt Widgets module. If you are porting applications from KDE Platform 4
    "kdeui" library, you will find many of its classes here.

    Provided are action classes that can be added to toolbars or menus,
    a wide range of widgets for selecting characters, fonts, colors, actions,
    dates and times, or MIME types, as well as platform-aware dialogs for
    configuration pages, message boxes, and password requests.
  dev_url: https://cgit.kde.org/kwidgetsaddons.git/tree

extra:
  recipe-maintainers:
    - scopatz
